-- See postgresql/V10__admin_moderation_and_settings.sql for rationale.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS banned boolean NOT NULL DEFAULT false;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS verified boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_username varchar(50) NOT NULL,
    target_username varchar(50) NOT NULL,
    reason varchar(500) NOT NULL,
    message_snippet varchar(300),
    status varchar(20) NOT NULL DEFAULT 'OPEN',
    created_at timestamp NOT NULL,
    resolved_by varchar(50),
    resolved_at timestamp
);

CREATE TABLE IF NOT EXISTS platform_settings (
    id smallint PRIMARY KEY,
    registration_enabled boolean NOT NULL DEFAULT true,
    group_creation_enabled boolean NOT NULL DEFAULT true,
    maintenance_mode boolean NOT NULL DEFAULT false,
    CONSTRAINT chk_platform_settings_singleton CHECK (id = 1)
);
MERGE INTO platform_settings (id) KEY(id) VALUES (1);

CREATE TABLE IF NOT EXISTS admin_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username varchar(50) NOT NULL,
    action varchar(50) NOT NULL,
    target varchar(100),
    details varchar(500),
    created_at timestamp NOT NULL
);
