-- See postgresql/V12__password_reset.sql for rationale.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS email varchar(150);

CREATE TABLE IF NOT EXISTS password_reset_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    token varchar(100) NOT NULL,
    expires_at timestamp NOT NULL,
    used boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_token_token ON password_reset_token (token);
