-- Baseline migration for the H2 fallback profile (--spring.profiles.active=h2). Mirrors the
-- postgresql baseline; kept idempotent for the same reasons.

CREATE TABLE IF NOT EXISTS app_user (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(50)  NOT NULL UNIQUE,
    password             varchar(255) NOT NULL,
    display_name         varchar(100) NOT NULL,
    avatar_url           varchar(255),
    status               varchar(140),
    online               boolean      NOT NULL DEFAULT false,
    last_seen            timestamp,
    show_online_status   boolean      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS board_post (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                varchar(20)   NOT NULL,
    title               varchar(150)  NOT NULL,
    description         varchar(2000),
    event_at            timestamp,
    status              varchar(20),
    assignee_username   varchar(50),
    start_at            timestamp,
    author_username     varchar(50)   NOT NULL,
    created_at          timestamp     NOT NULL
);

CREATE TABLE IF NOT EXISTS news_post (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             varchar(150)  NOT NULL,
    content           varchar(4000) NOT NULL,
    image_url         varchar(255),
    author_username   varchar(50)   NOT NULL,
    created_at        timestamp     NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_group (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    avatar_url   varchar(255),
    type         varchar(20)  NOT NULL,
    created_by   varchar(50)  NOT NULL,
    created_at   timestamp    NOT NULL
);

CREATE TABLE IF NOT EXISTS group_member (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    bigint      NOT NULL REFERENCES chat_group (id),
    username    varchar(50) NOT NULL,
    joined_at   timestamp   NOT NULL,
    CONSTRAINT uk_group_member_group_username UNIQUE (group_id, username)
);
