-- See postgresql/V8__profile_extras_and_blocking.sql for rationale.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS presence_status varchar(20);
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS job_title varchar(100);

CREATE TABLE IF NOT EXISTS blocked_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_username varchar(50) NOT NULL,
    blocked_username varchar(50) NOT NULL,
    created_at timestamp NOT NULL,
    CONSTRAINT uq_blocked_user UNIQUE (blocker_username, blocked_username)
);

CREATE TABLE IF NOT EXISTS user_sticker (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_username varchar(50) NOT NULL,
    url varchar(255) NOT NULL,
    created_at timestamp NOT NULL
);
