-- See postgresql/V9__admin_dashboard_analytics.sql for rationale.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
UPDATE app_user SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE app_user ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE app_user ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS daily_message_stats (
    stat_date DATE PRIMARY KEY,
    message_count BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS daily_group_message_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date DATE NOT NULL,
    group_id BIGINT NOT NULL,
    message_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_daily_group_message_stats UNIQUE (stat_date, group_id)
);
