-- Optional email address, set by the user themselves in profile settings; needed so
-- "forgot password" has somewhere to send a reset link. Uniqueness is enforced in the
-- application layer (like username) rather than a DB constraint, to keep NULLs simple
-- across both the postgresql and h2 profiles.
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS email varchar(150);

-- One-time tokens for the "forgot password" flow. A row is consumed (used = true) the
-- moment it's redeemed, and is also time-limited via expires_at, so a leaked/old email
-- link can't be replayed indefinitely.
CREATE TABLE IF NOT EXISTS password_reset_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    token varchar(100) NOT NULL,
    expires_at timestamp NOT NULL,
    used boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_token_token ON password_reset_token (token);
