-- Baseline migration: describes the schema as it already exists in the running database
-- (previously managed by hibernate.ddl-auto=update). Everything is IF NOT EXISTS / idempotent
-- so this is safe to run both against a brand-new empty database and against the existing
-- populated one when Flyway is adopted for the first time.

CREATE TABLE IF NOT EXISTS app_user (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(50)  NOT NULL,
    password             varchar(255) NOT NULL,
    display_name         varchar(100) NOT NULL,
    avatar_url           varchar(255),
    status               varchar(140),
    online               boolean      NOT NULL DEFAULT false,
    last_seen            timestamp,
    show_online_status   boolean      NOT NULL DEFAULT true,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

-- Safety net in case an earlier hibernate ddl-auto=update run created the table without this
-- column (NOT NULL + DEFAULT lets Postgres backfill existing rows).
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS show_online_status boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS board_post (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                varchar(20)   NOT NULL,
    title               varchar(150)  NOT NULL,
    description         varchar(2000),
    event_at            timestamp,
    status              varchar(20),
    assignee_username   varchar(50),
    start_at            timestamp,
    author_username     varchar(50)   NOT NULL,
    created_at          timestamp     NOT NULL
);

ALTER TABLE board_post ADD COLUMN IF NOT EXISTS assignee_username varchar(50);
ALTER TABLE board_post ADD COLUMN IF NOT EXISTS start_at timestamp;

CREATE TABLE IF NOT EXISTS news_post (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             varchar(150)  NOT NULL,
    content           varchar(4000) NOT NULL,
    image_url         varchar(255),
    author_username   varchar(50)   NOT NULL,
    created_at        timestamp     NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_group (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    avatar_url   varchar(255),
    type         varchar(20)  NOT NULL,
    created_by   varchar(50)  NOT NULL,
    created_at   timestamp    NOT NULL
);

CREATE TABLE IF NOT EXISTS group_member (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    bigint      NOT NULL REFERENCES chat_group (id),
    username    varchar(50) NOT NULL,
    joined_at   timestamp   NOT NULL,
    CONSTRAINT uk_group_member_group_username UNIQUE (group_id, username)
);
